name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: docker login
        env:
          DOCKER_USER:  ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag l1ghtman/scoretrakweb:latest
      - name: Push the Docker image
        run: docker push l1ghtman/scoretrakweb:latest
