name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Download golang environment"
        uses: actions/setup-go@v2
      - run: go version
      - run: go mod tidy
      - name: "Download Cockroach DB"
        run: wget -qO- https://binaries.cockroachdb.com/cockroach-v20.1.1.linux-amd64.tgz | tar  xvz
      - name: "Move Cockroach DB to /usr/local/bin/"
        run: sudo cp -i cockroach-v20.1.1.linux-amd64/cockroach /usr/local/bin/
      - name: "Start Cockroach DB in background"
        run: cockroach start-single-node --insecure --background
      - name: "Download gobuffalo"
        run: wget https://github.com/gobuffalo/buffalo/releases/download/v0.16.10/buffalo_0.16.10_Linux_x86_64.tar.gz
      - run: tar -xvzf buffalo_0.16.10_Linux_x86_64.tar.gz
      - run: sudo mv buffalo /usr/local/bin/buffalo
      - run: buffalo pop create -a
      - run: buffalo pop migrate
      - run: buffalo test